import type { Customer, Order, WindowItem, InstallationPhoto, PaymentRecord, InstallationAppointment, FollowUpRecord, ContractConfirmation, InspectionRecord, AfterSalesTicket } from "./types";

const now = new Date();
const daysAgo = (d: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - d);
  return date.toISOString();
};

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    name: "张伟",
    phone: "13812345678",
    address: "上海市浦东新区张江高科技园区博云路2号5栋1801",
    createdAt: daysAgo(90),
  },
  {
    id: "cust-002",
    name: "李娜",
    phone: "13987654321",
    address: "上海市徐汇区漕宝路88号光大会展中心B座2203",
    createdAt: daysAgo(75),
  },
  {
    id: "cust-003",
    name: "王建国",
    phone: "13600001234",
    address: "上海市闵行区七宝镇宝铭路88弄12号602",
    createdAt: daysAgo(60),
  },
  {
    id: "cust-004",
    name: "陈美玲",
    phone: "13722223333",
    address: "上海市静安区南京西路1788号国际中心3501",
    createdAt: daysAgo(45),
  },
  {
    id: "cust-005",
    name: "刘强",
    phone: "13855556666",
    address: "上海市杨浦区五角场街道黄兴路2218号合生汇1502",
    createdAt: daysAgo(30),
  },
  {
    id: "cust-006",
    name: "赵芳",
    phone: "13977778888",
    address: "上海市长宁区虹桥路1438号古北财富中心2801",
    createdAt: daysAgo(15),
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    customerId: "cust-001",
    orderNo: "MC20260401001",
    status: "completed",
    totalAmount: 28600,
    totalProfileMeters: 52.8,
    totalGlassArea: 26.4,
    createdAt: daysAgo(78),
    updatedAt: daysAgo(60),
    completedAt: daysAgo(60),
  },
  {
    id: "ord-002",
    customerId: "cust-002",
    orderNo: "MC20260415002",
    status: "completed",
    totalAmount: 42300,
    totalProfileMeters: 78.6,
    totalGlassArea: 39.2,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(48),
    completedAt: daysAgo(48),
  },
  {
    id: "ord-003",
    customerId: "cust-001",
    orderNo: "MC20260502003",
    status: "completed",
    totalAmount: 15800,
    totalProfileMeters: 29.4,
    totalGlassArea: 14.7,
    createdAt: daysAgo(47),
    updatedAt: daysAgo(33),
    completedAt: daysAgo(33),
  },
  {
    id: "ord-004",
    customerId: "cust-003",
    orderNo: "MC20260510004",
    status: "installing",
    totalAmount: 56200,
    totalProfileMeters: 104.2,
    totalGlassArea: 51.8,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(3),
    paymentDueDate: daysAgo(-7).split("T")[0],
  },
  {
    id: "ord-005",
    customerId: "cust-004",
    orderNo: "MC20260520005",
    status: "shipped",
    totalAmount: 33500,
    totalProfileMeters: 61.4,
    totalGlassArea: 30.6,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(5),
    paymentDueDate: daysAgo(10).split("T")[0],
  },
  {
    id: "ord-006",
    customerId: "cust-005",
    orderNo: "MC20260601006",
    status: "producing",
    totalAmount: 21800,
    totalProfileMeters: 40.2,
    totalGlassArea: 20.1,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(10),
    paymentDueDate: daysAgo(-15).split("T")[0],
  },
  {
    id: "ord-007",
    customerId: "cust-002",
    orderNo: "MC20260605007",
    status: "producing",
    totalAmount: 47600,
    totalProfileMeters: 88.6,
    totalGlassArea: 44.2,
    createdAt: daysAgo(13),
    updatedAt: daysAgo(8),
    paymentDueDate: daysAgo(5).split("T")[0],
  },
  {
    id: "ord-008",
    customerId: "cust-006",
    orderNo: "MC20260610008",
    status: "placed",
    totalAmount: 19200,
    totalProfileMeters: 35.6,
    totalGlassArea: 17.8,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
    paymentDueDate: daysAgo(-20).split("T")[0],
  },
  {
    id: "ord-009",
    customerId: "cust-003",
    orderNo: "MC20260612009",
    status: "placed",
    totalAmount: 38900,
    totalProfileMeters: 72.4,
    totalGlassArea: 36.1,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    paymentDueDate: daysAgo(-25).split("T")[0],
  },
  {
    id: "ord-010",
    customerId: "cust-006",
    orderNo: "MC20260615010",
    status: "placed",
    totalAmount: 26500,
    totalProfileMeters: 48.8,
    totalGlassArea: 24.4,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    remark: "客户要求本月底前安装完成",
    paymentDueDate: daysAgo(-30).split("T")[0],
  },
];

export const mockWindowItems: WindowItem[] = [
  { id: "wi-001", orderId: "ord-001", widthMm: 1500, heightMm: 1800, profileColor: "深咖色", glassType: "double", hardwareBrand: "好博 HOPO", unitPrice: 6800, quantity: 2 },
  { id: "wi-002", orderId: "ord-001", widthMm: 1200, heightMm: 1500, profileColor: "深咖色", glassType: "double", hardwareBrand: "好博 HOPO", unitPrice: 5000, quantity: 3 },
  { id: "wi-003", orderId: "ord-002", widthMm: 2000, heightMm: 2200, profileColor: "砂灰色", glassType: "double", hardwareBrand: "坚朗 KINLONG", unitPrice: 12800, quantity: 2 },
  { id: "wi-004", orderId: "ord-002", widthMm: 1800, heightMm: 2000, profileColor: "砂灰色", glassType: "double", hardwareBrand: "坚朗 KINLONG", unitPrice: 9200, quantity: 2 },
  { id: "wi-005", orderId: "ord-003", widthMm: 1000, heightMm: 1200, profileColor: "象牙白", glassType: "single", hardwareBrand: "国强", unitPrice: 3200, quantity: 3 },
  { id: "wi-006", orderId: "ord-003", widthMm: 1500, heightMm: 1500, profileColor: "象牙白", glassType: "single", hardwareBrand: "国强", unitPrice: 6200, quantity: 1 },
  { id: "wi-007", orderId: "ord-004", widthMm: 2400, heightMm: 2400, profileColor: "氟碳金", glassType: "double", hardwareBrand: "丝吉利娅", unitPrice: 18800, quantity: 2 },
  { id: "wi-008", orderId: "ord-004", widthMm: 1800, heightMm: 2100, profileColor: "氟碳金", glassType: "double", hardwareBrand: "丝吉利娅", unitPrice: 9800, quantity: 2 },
  { id: "wi-009", orderId: "ord-005", widthMm: 1600, heightMm: 1900, profileColor: "红酸枝", glassType: "double", hardwareBrand: "诺托 ROTO", unitPrice: 8600, quantity: 2 },
  { id: "wi-010", orderId: "ord-005", widthMm: 1400, heightMm: 1700, profileColor: "红酸枝", glassType: "double", hardwareBrand: "诺托 ROTO", unitPrice: 6500, quantity: 2 },
  { id: "wi-011", orderId: "ord-006", widthMm: 1200, heightMm: 1600, profileColor: "黄花梨", glassType: "single", hardwareBrand: "合和", unitPrice: 4800, quantity: 2 },
  { id: "wi-012", orderId: "ord-006", widthMm: 1100, heightMm: 1400, profileColor: "黄花梨", glassType: "single", hardwareBrand: "合和", unitPrice: 3600, quantity: 3 },
  { id: "wi-013", orderId: "ord-007", widthMm: 2200, heightMm: 2300, profileColor: "香槟色", glassType: "double", hardwareBrand: "好博 HOPO", unitPrice: 14800, quantity: 2 },
  { id: "wi-014", orderId: "ord-007", widthMm: 1700, heightMm: 2000, profileColor: "香槟色", glassType: "double", hardwareBrand: "好博 HOPO", unitPrice: 9000, quantity: 2 },
  { id: "wi-015", orderId: "ord-008", widthMm: 1300, heightMm: 1700, profileColor: "墨绿色", glassType: "single", hardwareBrand: "春晖", unitPrice: 5200, quantity: 2 },
  { id: "wi-016", orderId: "ord-008", widthMm: 1000, heightMm: 1400, profileColor: "墨绿色", glassType: "single", hardwareBrand: "春晖", unitPrice: 3200, quantity: 2 },
  { id: "wi-017", orderId: "ord-009", widthMm: 2000, heightMm: 2400, profileColor: "砂灰色", glassType: "double", hardwareBrand: "坚朗 KINLONG", unitPrice: 13500, quantity: 2 },
  { id: "wi-018", orderId: "ord-009", widthMm: 1600, heightMm: 1900, profileColor: "深咖色", glassType: "double", hardwareBrand: "好博 HOPO", unitPrice: 7900, quantity: 1 },
  { id: "wi-019", orderId: "ord-010", widthMm: 1800, heightMm: 2000, profileColor: "象牙白", glassType: "double", hardwareBrand: "国强", unitPrice: 8200, quantity: 2 },
  { id: "wi-020", orderId: "ord-010", widthMm: 1200, heightMm: 1500, profileColor: "象牙白", glassType: "double", hardwareBrand: "国强", unitPrice: 5000, quantity: 2 },
];

export const mockPhotos: InstallationPhoto[] = [
  {
    id: "photo-001",
    orderId: "ord-001",
    dataUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20house%20interior%20with%20dark%20brown%20aluminum%20windows%20and%20double%20glass%2C%20warm%20sunlight%20coming%20through%2C%20clean%20installation%20finish&image_size=landscape_4_3",
    uploadedAt: daysAgo(60),
  },
  {
    id: "photo-002",
    orderId: "ord-002",
    dataUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=luxury%20apartment%20floor%20to%20ceiling%20grey%20aluminum%20windows%20with%20city%20view%2C%20professional%20installation&image_size=landscape_4_3",
    uploadedAt: daysAgo(48),
  },
  {
    id: "photo-003",
    orderId: "ord-003",
    dataUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cozy%20bedroom%20with%20white%20frame%20windows%2C%20single%20glass%2C%20neatly%20installed%20with%20curtains&image_size=landscape_4_3",
    uploadedAt: daysAgo(33),
  },
];

export const mockPayments: PaymentRecord[] = [
  { id: "pay-001", orderId: "ord-001", amount: 10000, paymentType: "deposit", paymentDate: daysAgo(78).split("T")[0], remark: "下单时支付定金30%", createdAt: daysAgo(78) },
  { id: "pay-002", orderId: "ord-001", amount: 18600, paymentType: "balance", paymentDate: daysAgo(60).split("T")[0], remark: "安装验收合格后付清尾款", createdAt: daysAgo(60) },
  { id: "pay-003", orderId: "ord-002", amount: 15000, paymentType: "deposit", paymentDate: daysAgo(65).split("T")[0], remark: "定金", createdAt: daysAgo(65) },
  { id: "pay-004", orderId: "ord-002", amount: 27300, paymentType: "balance", paymentDate: daysAgo(48).split("T")[0], remark: "完工结清", createdAt: daysAgo(48) },
  { id: "pay-005", orderId: "ord-003", amount: 6000, paymentType: "deposit", paymentDate: daysAgo(47).split("T")[0], remark: "", createdAt: daysAgo(47) },
  { id: "pay-006", orderId: "ord-003", amount: 9800, paymentType: "balance", paymentDate: daysAgo(33).split("T")[0], remark: "", createdAt: daysAgo(33) },
  { id: "pay-007", orderId: "ord-004", amount: 20000, paymentType: "deposit", paymentDate: daysAgo(38).split("T")[0], remark: "30%定金", createdAt: daysAgo(38) },
  { id: "pay-008", orderId: "ord-004", amount: 20000, paymentType: "installment", paymentDate: daysAgo(10).split("T")[0], remark: "生产进度款", createdAt: daysAgo(10) },
  { id: "pay-009", orderId: "ord-005", amount: 12000, paymentType: "deposit", paymentDate: daysAgo(28).split("T")[0], remark: "", createdAt: daysAgo(28) },
  { id: "pay-010", orderId: "ord-006", amount: 8000, paymentType: "deposit", paymentDate: daysAgo(17).split("T")[0], remark: "", createdAt: daysAgo(17) },
  { id: "pay-011", orderId: "ord-007", amount: 15000, paymentType: "deposit", paymentDate: daysAgo(13).split("T")[0], remark: "老客户，优惠500", createdAt: daysAgo(13) },
  { id: "pay-012", orderId: "ord-008", amount: 5000, paymentType: "deposit", paymentDate: daysAgo(8).split("T")[0], remark: "", createdAt: daysAgo(8) },
  { id: "pay-013", orderId: "ord-009", amount: 10000, paymentType: "deposit", paymentDate: daysAgo(6).split("T")[0], remark: "王总介绍的客户", createdAt: daysAgo(6) },
];

export const mockAppointments: InstallationAppointment[] = [
  {
    id: "apt-001",
    orderId: "ord-004",
    appointmentDate: daysAgo(-2).split("T")[0],
    installer: "李师傅",
    remark: "客户要求上午9点到达，需要自带鞋套",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "apt-002",
    orderId: "ord-005",
    appointmentDate: daysAgo(-5).split("T")[0],
    installer: "张师傅",
    remark: "小区停车方便，从西门进",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "apt-003",
    orderId: "ord-010",
    appointmentDate: daysAgo(-1).split("T")[0],
    installer: "王师傅",
    remark: "客户要求月底前安装完成",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

export const mockFollowUps: FollowUpRecord[] = [
  {
    id: "fu-001",
    customerId: "cust-001",
    contactDate: daysAgo(10).split("T")[0],
    content: "客户来电询问生产进度，担心能否按时安装",
    result: "告知客户已完成生产，待发货，预计3天内到货",
    nextFollowUpDate: daysAgo(-3).split("T")[0],
    createdAt: daysAgo(10),
  },
  {
    id: "fu-002",
    customerId: "cust-001",
    contactDate: daysAgo(3).split("T")[0],
    content: "客户回访安装使用情况，询问保养方法",
    result: "告知客户清洁注意事项，留下联系方式有问题随时联系",
    createdAt: daysAgo(3),
  },
  {
    id: "fu-003",
    customerId: "cust-003",
    contactDate: daysAgo(5).split("T")[0],
    content: "客户来电咨询新款窗型，考虑阳台加装",
    result: "已发送产品资料，约定下周上门测量",
    nextFollowUpDate: daysAgo(-2).split("T")[0],
    createdAt: daysAgo(5),
  },
  {
    id: "fu-004",
    customerId: "cust-002",
    contactDate: daysAgo(8).split("T")[0],
    content: "客户反映窗边有轻微渗水，需要处理",
    result: "已安排师傅上门打胶处理，客户满意",
    createdAt: daysAgo(8),
  },
  {
    id: "fu-005",
    customerId: "cust-004",
    contactDate: daysAgo(2).split("T")[0],
    content: "客户询问发货时间，比较着急",
    result: "告知客户已发货，明天到达，预约后天安装",
    createdAt: daysAgo(2),
  },
];

export const mockContracts: ContractConfirmation[] = [
  {
    id: "contract-001",
    orderId: "ord-004",
    paymentTerms: "签订合同支付30%定金，生产完毕支付40%进度款，安装验收合格后付清30%尾款",
    installationTerms: "预计15个工作日生产完成，上门安装预计2个工作日。安装前请客户清理安装现场，确保水电到位。",
    warrantyMonths: 24,
    customerSignature: "王建国",
    signedAt: daysAgo(37),
    createdAt: daysAgo(38),
    updatedAt: daysAgo(37),
  },
  {
    id: "contract-002",
    orderId: "ord-005",
    paymentTerms: "支付50%定金，安装验收合格后付清50%尾款",
    installationTerms: "生产周期20个工作日，安装1天。客户家中有宠物，请安装师傅注意关好门窗。",
    warrantyMonths: 12,
    customerSignature: "陈美玲",
    signedAt: daysAgo(27),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(27),
  },
  {
    id: "contract-003",
    orderId: "ord-001",
    paymentTerms: "一次性付清全款，享受95折优惠",
    installationTerms: "生产周期10个工作日，安装半天。小区物业规定周末不能施工，请安排工作日安装。",
    warrantyMonths: 24,
    customerSignature: "张伟",
    signedAt: daysAgo(77),
    createdAt: daysAgo(78),
    updatedAt: daysAgo(77),
  },
];

export const mockInspections: InspectionRecord[] = [
  {
    id: "insp-001",
    orderId: "ord-001",
    inspectionDate: daysAgo(60).split("T")[0],
    result: "pass",
    customerFeedback: "安装质量很好，密封处理到位，开关顺畅，非常满意！",
    needsRework: false,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
  {
    id: "insp-002",
    orderId: "ord-002",
    inspectionDate: daysAgo(48).split("T")[0],
    result: "pass",
    customerFeedback: "整体满意，大落地窗效果很好，就是有一个窗户把手有点松，师傅当场调整好了。",
    needsRework: false,
    createdAt: daysAgo(48),
    updatedAt: daysAgo(48),
  },
  {
    id: "insp-003",
    orderId: "ord-003",
    inspectionDate: daysAgo(35).split("T")[0],
    result: "rework",
    customerFeedback: "发现主卧室窗户右下角有轻微渗水痕迹，需要重新打胶处理。",
    needsRework: true,
    reworkReason: "窗户边角密封胶施工不到位，导致雨天渗水",
    reworkProgress: "已安排师傅上门重新打胶，等待雨天测试效果",
    reworkCompletedAt: daysAgo(33),
    createdAt: daysAgo(35),
    updatedAt: daysAgo(33),
  },
];

export const mockAfterSalesTickets: AfterSalesTicket[] = [
  {
    id: "as-001",
    customerId: "cust-002",
    orderId: "ord-002",
    issueType: "五金松动",
    description: "客户反映客厅大窗户的把手使用半年后有点松动，开关时有点晃",
    appointmentDate: daysAgo(15).split("T")[0],
    handler: "李师傅",
    status: "completed",
    result: "上门紧固把手螺丝，调整了传动器，现在开关顺畅。客户表示满意。",
    completedAt: daysAgo(15),
    createdAt: daysAgo(16),
    updatedAt: daysAgo(15),
  },
  {
    id: "as-002",
    customerId: "cust-003",
    orderId: "ord-004",
    issueType: "漏水问题",
    description: "客户说下雨时阳台窗框底部有点渗水，担心泡坏木地板",
    appointmentDate: daysAgo(5).split("T")[0],
    handler: "张师傅",
    status: "processing",
    result: "已上门检查，发现是排水孔堵塞导致积水。已清理排水孔并重新打胶，观察后续效果。",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: "as-003",
    customerId: "cust-001",
    orderId: "ord-003",
    issueType: "密封条老化",
    description: "次卧窗户使用1年后，密封胶条有点变硬，担心密封效果下降",
    appointmentDate: daysAgo(-3).split("T")[0],
    handler: "王师傅",
    status: "pending",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "as-004",
    customerId: "cust-005",
    issueType: "开关不畅",
    description: "厨房窗户最近开关有点卡，需要用力才能关上",
    handler: "李师傅",
    status: "pending",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
];
